# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Coverage configuration
# ----------------------
codecov:
  require_ci_to_pass: yes

ignore:
  - "src/legacy"
  - "src/function/src/aws"
  - "src/driver/src/build"
  - "src/bin/cli"
  - "**/*.md"
  - "benchmarks"

coverage:
  status:
    project:
      default:
        target: 80% # the required coverage value
        threshold: 2% # the leniency in hitting the target
    patch:
      default:
        target: 80% # the required coverage value
        threshold: 2% # the leniency in hitting the target
