[project]

name = "flock"
discription = "Flock: A Practical Serverless Streaming SQL Query Engine"
license = "Copyright (c) 2020-present, UMD Database Group. The library, examples, and all source code are released AGPL-3.0 License."
production = false

[lambda]

name = "execution_context"

# default target batch size (16 KB)
target_batch_size = 16384

# default raw record batch size in the payload (512 KB)
payload_batch_size = 524288

# multi-thread parallelism inside the cloud function
parallelism = 8

join_threshold = 5242880
aggregate_threshold = 10485760
regular_threshold = 20971520

# default s3 address to store the generic function code
s3_bucket = "umd-flock"
s3_key = "flock"
s3_nexmark_key = "nexmark"
s3_nexmark_q4_plan_key = "nexmark_q4_plan"
s3_nexmark_q6_plan_key = "nexmark_q6_plan"

# the granularity of each type of data in the payload
granule = 3096 
