[flock]

discription = "Flock: A Practical Serverless Streaming SQL Query Engine"
license = "Copyright (c) 2020-present, UMD Database Group. The library, examples, and all source code are released AGPL-3.0 License."
production = false

# default s3 address to store the generic function code
s3_bucket = "flock-lab"
s3_key = "flock"

[lambda]

environment = "execution_context"

# default target batch size (16 KB)
target_batch_size = 16384

# default raw record batch size in the payload (512 KB)
payload_batch_size = 524288

# lambda function concurrency
concurrency = 8

join_threshold = 5242880
aggregate_threshold = 10485760
regular_threshold = 20971520

# the granularity of each type of data in the payload
async_granule = 3096
sync_granule = 74304

[nexmark]

s3_key = "nexmark"
q4_s3_key = "nexmark_q4_plan"
q6_s3_key = "nexmark_q6_plan"

[ysb]

s3_key = "ysb"
