# https://github.com/johnthagen/min-sized-rust#optimize-libstd-with-xargo
[dependencies]
std = {default-features=false, features=["panic_immediate_abort"]}

# Build
# xargo build --target x86_64-unknown-linux-gnu --release
