[package]
name = "lambda-operators"
version = "0.1.0"
description = "The generic lambda functions for cloud environment execution."
authors = [ "Gang Liao <gangliao@cs.umd.edu>" ]
license = "Apache-2.0"
keywords = [ "AWS", "pre-compiled", "lambda", "S3" ]
edition = "2018"

[features]
snmalloc = [ "snmalloc-rs" ]

[dependencies]
aws_lambda_events = "0.4"
daggy = "0.7.0"
datafusion = { git = "https://github.com/DSLAM-UMD/arrow", branch = "scq", features = [ "simd" ] }
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master" }
scq_lambda = { path = "../../lambda" }
serde_json = "1.0"
snmalloc-rs = { version = "0.2", optional = true, features = [ "cache-friendly" ] }
tokio = { version = "0.2", features = [ "macros" ] }

[[bin]]
name = "scq_ops"
path = "src/ops.rs"

[[bin]]
name = "scq_kinesis"
path = "src/kinesis.rs"
