[package]
name = "scq_driver"
version = "0.1.0"
description = "A library to generate, compile and deploy lambda functions to the cloud."
authors = [ "Gang Liao <gangliao@cs.umd.edu>", "Zejun Liu <zliu1238@cs.umd.edu>" ]
license = "Apache-2.0"
keywords = [ "AWS", "code generation", "compilation", "build", "continuous deployment" ]
edition = "2018"

[dependencies]
arrow = { git = "https://github.com/DSLAM-UMD/arrow", branch = "scq" }
arrow-flight = { git = "https://github.com/DSLAM-UMD/arrow", branch = "scq" }
cargo = "0.50.0"
codegen = "0.1.3"
json = "0.12.4"
regex = "1.4.3"

serde = { version = "1.0", features = [ "derive" ] }
serde_bytes = "0.11"
serde_json = "1.0"

[lib]
name = "scq_driver"
path = "src/lib.rs"
crate-type = [ "lib" ]
