[package]
name = "scq_driver"
version = "0.1.0"
description = "A library to generate, compile and deploy lambda functions to the cloud."
authors = [ "Gang Liao <gangliao@cs.umd.edu>", "Zejun Liu <zliu1238@cs.umd.edu>" ]
license = "Apache-2.0"
keywords = [ "AWS", "code generation", "compilation", "build", "continuous deployment" ]
edition = "2018"

[dependencies]
cargo = "0.50.0"
filetime = "0.2"
glob = "0.3"
handlebars = "3.5.2"
lazy_static = "1.4"
num_cpus = "1.13.0"
regex = "1.4.3"
remove_dir_all = "0.6"
scq_lambda = { path = "../../src/lambda" }
serde_json = "1.0"
url = "2.0"

[lib]
name = "scq_driver"
path = "src/lib.rs"
crate-type = [ "lib" ]
