[package]
name = "driver"
version = "0.1.0"
authors = ["Gang Liao <gangliao@cs.umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = {version = "0.6.1", features = ["json_example"]}
tokio = { version = "0.2", features = ["macros"] }
serde_json = "1.0"
