[package]
name = "squirtle-cli"
version = "0.1.0"
description = "A command-line REPL for Squirtle that integrates into existing cli workflows"
authors = [ "Gang Liao <gangliao@cs.umd.edu>" ]
license = "Apache-2.0"
keywords = [ "Squirtle", "repl", "client", "cli" ]
categories = [ "command-line-interface", "command-line-utilities" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "cli" ]
cli = [ "rustyline" ]

[dependencies]
clap = "2.33.3"
ctrlc = "3.1.1"
futures = "0.3.12"
lazy_static = "1.4.0"
runtime = { path = "../../runtime" }
rusoto_core = "0.47.0"
rusoto_s3 = "0.46.0"
rustyline = { version = "8.0", optional = true }
sqlparser = { version = "0.9.0", features = [ "json_example" ] }
tokio = { version = "1.2", features = [ "macros", "io-util", "sync", "rt-multi-thread" ] }
zip = "0.5.12"

[[bin]]
name = "squirtle-cli"
path = "src/main.rs"
