[package]
name = "serverlesscq-cli"
version = "0.1.0"
description = "A command-line REPL for ServerlessCQ that integrates into existing cli workflows"
authors = [ "Gang Liao <gangliao@cs.umd.edu>" ]
license = "Apache-2.0"
keywords = [ "ServerlessCQ", "repl", "client", "cli" ]
categories = [ "command-line-interface", "command-line-utilities" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "cli" ]
cli = [ "rustyline" ]

[dependencies]
clap = "2.33.3"
ctrlc = "3.1.1"

lazy_static = "1.4.0"
rustyline = { version = "7.0", optional = true }
scq_lambda = { path = "../../lambda" }
sqlparser = { version = "0.7.0", features = [ "json_example" ] }
tokio = { version = "0.2", features = [ "macros" ] }

[[bin]]
name = "serverlesscq-cli"
path = "src/main.rs"
