name: Rust

on:
  schedule:
    # Runs "at 12:00." (see https://crontab.guru)
    - cron: '0 12 * * *'

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # a list of all the targets
        include:
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-latest
            RUST: nightly
          - TARGET: x86_64-unknown-linux-musl
            OS: ubuntu-latest
            RUST: nightly
          - TARGET: aarch64-unknown-linux-gnu
            OS: ubuntu-latest
            RUST: nightly
          # - TARGET: aarch64-unknown-linux-musl
          #   OS: ubuntu-latest
          #   RUST: nightly
    # if: github.ref != 'refs/heads/master'
    runs-on: ${{ matrix.OS }}
    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      # Disable full debug symbol generation to speed up CI build and keep memory down
      # "1" means line tables only, which is useful for panic tracebacks.
      RUSTFLAGS: "-C debuginfo=1"
    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          # these represent dependencies downloaded by cargo
          # and thus do not depend on the OS, arch nor rust version.
          path: ~/.cargo
          key: cargo-cache-
      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          # these represent compiled steps of both dependencies and arrow
          # and thus are specific for a particular OS, arch and rust version.
          path: target
          key: ${{ runner.os }}-${{ matrix.TARGET }}-target-cache-${{ matrix.RUST }}-
      - name: Setup Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.RUST }}
          rustup default ${{ matrix.RUST }}
          rustup component add rustfmt
      # - name: update all third-party dependencies
      #   run: |
      #     cargo update
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'benchmarks/**'
              - 'flock/**'
              - 'flock-cli/**'
              - 'flock-function/**'
              - 'playground/**'
      - name: Install and configure dependencies
        run: |
          # dependencies are only needed on ubuntu as that's the only place where
          # we make cross-compilation
          if [[ $OS =~ ^ubuntu.*$ ]]; then
            sudo apt install musl-tools
            sudo apt-get install -qq crossbuild-essential-arm64 crossbuild-essential-armhf
            wget http://more.musl.cc/$(uname -m)-linux-musl/aarch64-linux-musl-cross.tgz
            tar -xvf aarch64-linux-musl-cross.tgz
            sudo mv aarch64-linux-musl-cross /opt/
            echo 'export PATH=/opt/aarch64-linux-musl-cross/bin:$PATH' >> ~/.bashrc
            source ~/.bashrc
          fi
          # some additional configuration for cross-compilation on linux
          cat >>~/.cargo/config <<EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          [target.aarch64-unknown-linux-musl]
          linker = "/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
          ar = "/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc-ar"
          rustflags = [ "-C", "link-arg=-lgcc", "-C", "link-arg=/opt/aarch64-linux-musl-cross/aarch64-linux-musl/lib/libc.a" ]
          EOF
      - name: Install rust target
        if: steps.changes.outputs.src == 'true'
        run: rustup target add $TARGET
      - name: Run build
        if: steps.changes.outputs.src == 'true'
        run: |
          cargo +nightly build --release --verbose --target $TARGET --features "simd mimalloc"
        env:
          CARGO_HOME: "~/.cargo"
          CARGO_TARGET_DIR: "target"
          CC_aarch64-unknown-linux-musl: "/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
      - name: List target
        run: find ./target || true
      - name: Compress
        if: steps.changes.outputs.src == 'true'
        run: |
          mkdir -p ./artifacts
          if [[ $GITHUB_REF_TYPE =~ ^tag$ ]]; then
            TAG=$GITHUB_REF_NAME
          else
            TAG=$GITHUB_SHA
          fi
          mv ./target/$TARGET/release/flock flock
          mv ./target/$TARGET/release/flock-cli flock-cli
          strip --strip-all flock
          tar -czf ./artifacts/flock-$TARGET-$TAG.tar.gz flock flock-cli
      - name: Archive artifact
        if: steps.changes.outputs.src == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            ./artifacts
  test:
    strategy:
      fail-fast: false
      matrix:
        # a list of all the targets
        include:
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-latest
            RUST: nightly
    runs-on: ${{ matrix.OS }}
    needs: build
    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      # Disable full debug symbol generation to speed up CI build and keep memory down
      # "1" means line tables only, which is useful for panic tracebacks.
      RUSTFLAGS: "-C debuginfo=1"
    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          # this key equals the ones on `build` for re-use
          key: cargo-cache-
      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: target
          # this key equals the ones on `build` for re-use
          key: ${{ runner.os }}-${{ matrix.TARGET }}-target-cache-${{ matrix.RUST }}-
      - name: Setup Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.RUST }}
          rustup default ${{ matrix.RUST }}
          rustup component add rustfmt
      # - name: update all third-party dependencies
      #   run: |
      #     cargo update
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'benchmarks/**'
              - 'flock/**'
              - 'flock-cli/**'
              - 'flock-function/**'
              - 'playground/**'
      - name: Install rust target
        if: steps.changes.outputs.src == 'true'
        run: rustup target add $TARGET
      - name: Run build
        if: steps.changes.outputs.src == 'true'
        run: |
          cargo +nightly test --target $TARGET
        env:
          CARGO_HOME: "~/.cargo"
          CARGO_TARGET_DIR: "target"

  # deploys to github releases on tag
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: result
          path: ./artifacts
      - name: List
        run: find ./artifacts || true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.tar.gz
